### ISSUE TITLE
Release improvement

### ISSUE THREAD

**Issue by jacen92** [Graupunkt/project-jericho#11]
A script should be able to concatenate all the .ps1 file to make the installation easier.
Like the minifier for css/js files.

**Comment by Graupunkt** [comment]
Sry I don't understand this. Do you want to create a compressed file,  to install the tool?

**Comment by jacen92** [comment]
The idea is to share one .ps1 script gathering all your scripts (to avoid the issue on win11)

**Comment by Graupunkt** [comment]
There is a reason why I decided to dot source (or our source) some code.

First of all, I separate different functions and forms in their own files. This makes editing very easy, because I have everything I need in this single file. If I would merge all code into one file I would be at around 20.000 lines, a nightmare. 

The second is I use for the big forms a dedicated editor. This one allows me to only export the code. If I would merge this into one file manually, it would be very difficult to maintain.

So I see here the benefit for win 11 users,  but the disadvantages are to bad. I am sure that I can find another solution for our win 11 users.

If some morons didn't create malware with a specific builder, we could create exe files from powershell scripts,  that would help much on win11. Nowadays most a/v generally block exe files that have been signed with that builder.
